'use client';

import JSZip from 'jszip';
import { useCallback, useMemo, useState } from 'react';
import {
  AlertCircle,
  Download,
  FileText,
  Globe,
  Sparkles,
  Upload,
} from 'lucide-react';

type InputMethod = 'file' | 'url' | 'paste';

type GeneratedClient = {
  projectName: string;
  files: Record<string, string>;
};

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export default function ApiSpecUploader() {
  const [dragActive, setDragActive] = useState(false);
  const [inputMethod, setInputMethod] = useState<InputMethod>('file');
  const [specContent, setSpecContent] = useState('');
  const [specUrl, setSpecUrl] = useState('');
  const [generated, setGenerated] = useState<GeneratedClient | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const inputOptions = useMemo(
    () => [
      { id: 'file' as const, label: 'Upload File', icon: FileText },
      { id: 'url' as const, label: 'Spec URL', icon: Globe },
      { id: 'paste' as const, label: 'Paste', icon: Upload },
    ],
    []
  );

  const handleDrag = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === 'dragenter' || e.type === 'dragover') {
      setDragActive(true);
    } else if (e.type === 'dragleave') {
      setDragActive(false);
    }
  }, []);

  const processText = useCallback(async (text: string) => {
    setLoading(true);
    setError(null);
    setGenerated(null);

    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ inputMethod: 'raw', spec: text }),
      });

      const data = (await res.json()) as any;
      if (!res.ok) {
        throw new Error(data?.error || 'Generation failed.');
      }

      setGenerated({ projectName: data.projectName, files: data.files });
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Generation failed.');
    } finally {
      setLoading(false);
    }
  }, []);

  const processUrl = useCallback(async () => {
    setLoading(true);
    setError(null);
    setGenerated(null);

    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ inputMethod: 'url', url: specUrl }),
      });

      const data = (await res.json()) as any;
      if (!res.ok) {
        throw new Error(data?.error || 'Generation failed.');
      }

      setGenerated({ projectName: data.projectName, files: data.files });
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Generation failed.');
    } finally {
      setLoading(false);
    }
  }, [specUrl]);

  const processFile = useCallback(
    async (file: File) => {
      const ok =
        file.type === 'application/json' ||
        file.name.endsWith('.yaml') ||
        file.name.endsWith('.yml') ||
        file.name.endsWith('.json');

      if (!ok) {
        setError('Please upload a valid JSON or YAML file.');
        return;
      }

      const text = await file.text();
      setSpecContent(text);
      await processText(text);
    },
    [processText]
  );

  const handleDrop = useCallback(
    async (e: React.DragEvent) => {
      e.preventDefault();
      e.stopPropagation();
      setDragActive(false);

      const file = e.dataTransfer.files?.[0];
      if (!file) return;
      await processFile(file);
    },
    [processFile]
  );

  const handleDownloadZip = useCallback(async () => {
    if (!generated) return;

    const zip = new JSZip();
    const root = zip.folder(generated.projectName) ?? zip;

    for (const [name, content] of Object.entries(generated.files)) {
      root.file(name, content);
    }

    root.file(
      'README.md',
      `# ${generated.projectName}\n\nGenerated by phnxbyte.\n\nFiles:\n${Object.keys(generated.files)
        .map((f) => `- ${f}`)
        .join('\n')}\n`
    );

    const blob = await zip.generateAsync({ type: 'blob' });
    downloadBlob(blob, `${generated.projectName}.zip`);
  }, [generated]);

  return (
    <div className='mx-auto w-full max-w-6xl px-4 py-10'>
      <div className='glass-card border-white/10'>
        <div className='p-6 md:p-8 border-b border-white/10 flex items-center gap-3'>
          <div className='p-2 bg-white/10 border border-white/10 rounded-lg'>
            <Sparkles className='w-5 h-5 text-white' />
          </div>
          <div>
            <h1 className='text-2xl md:text-3xl font-bold tracking-tight'>
              Spec Upload → Generate → Download
            </h1>
            <p className='text-sm text-white/55 mt-1'>
              Upload an OpenAPI spec (JSON/YAML) to generate types, schemas, a fetch client, and
              basic React hooks.
            </p>
          </div>
        </div>

        <div className='p-6 md:p-8'>
          <div className='flex flex-wrap gap-2 mb-6'>
            {inputOptions.map((m) => (
              <button
                key={m.id}
                type='button'
                onClick={() => setInputMethod(m.id)}
                className={
                  inputMethod === m.id
                    ? 'inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-white text-black font-semibold'
                    : 'inline-flex items-center gap-2 px-4 py-2 rounded-xl border border-white/10 bg-white/5 hover:bg-white/10 text-white/80 transition-colors'
                }
              >
                <m.icon className='w-4 h-4' />
                {m.label}
              </button>
            ))}
          </div>

          {inputMethod === 'file' && (
            <div
              className={
                dragActive
                  ? 'rounded-2xl border-2 border-dashed border-white/40 bg-white/5 p-10 text-center transition-colors'
                  : 'rounded-2xl border-2 border-dashed border-white/15 bg-black/10 p-10 text-center transition-colors'
              }
              onDragEnter={handleDrag}
              onDragLeave={handleDrag}
              onDragOver={handleDrag}
              onDrop={handleDrop}
            >
              <Upload className='w-10 h-10 text-white/70 mx-auto mb-3' />
              <p className='text-white/80'>
                <span className='font-semibold'>Drag & drop</span> your OpenAPI spec here
              </p>
              <p className='text-white/40 text-sm mt-1'>Supports .json, .yaml, .yml</p>

              <div className='mt-6'>
                <label className='cursor-pointer inline-flex items-center justify-center px-5 py-3 rounded-xl bg-white text-black font-semibold hover:bg-gray-200 transition-colors'>
                  Browse files
                  <input
                    type='file'
                    className='hidden'
                    accept='.json,.yaml,.yml'
                    onChange={(e) => e.target.files?.[0] && void processFile(e.target.files[0])}
                  />
                </label>
              </div>
            </div>
          )}

          {inputMethod === 'url' && (
            <div className='rounded-2xl border border-white/10 bg-white/5 p-5'>
              <label className='text-sm text-white/70'>OpenAPI URL</label>
              <div className='mt-2 flex gap-2'>
                <input
                  value={specUrl}
                  onChange={(e) => setSpecUrl(e.target.value)}
                  placeholder='https://example.com/openapi.yaml'
                  className='w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:ring-2 focus:ring-white/20 text-white placeholder:text-white/40'
                />
                <button
                  type='button'
                  onClick={() => void processUrl()}
                  disabled={loading || specUrl.trim().length === 0}
                  className='px-4 py-3 rounded-xl bg-white text-black font-semibold hover:bg-gray-200 transition-colors disabled:opacity-50'
                >
                  Generate
                </button>
              </div>
              <p className='text-xs text-white/40 mt-2'>
                Server fetches the URL (helps avoid browser CORS issues).
              </p>
            </div>
          )}

          {inputMethod === 'paste' && (
            <div className='rounded-2xl border border-white/10 bg-white/5 p-5'>
              <label className='text-sm text-white/70'>Paste OpenAPI JSON or YAML</label>
              <textarea
                value={specContent}
                onChange={(e) => setSpecContent(e.target.value)}
                placeholder='Paste your OpenAPI spec here…'
                className='mt-2 w-full min-h-55 rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:ring-2 focus:ring-white/20 text-white placeholder:text-white/40 font-mono text-xs'
              />
              <div className='mt-3 flex items-center justify-end'>
                <button
                  type='button'
                  onClick={() => void processText(specContent)}
                  disabled={loading || specContent.trim().length === 0}
                  className='px-4 py-3 rounded-xl bg-white text-black font-semibold hover:bg-gray-200 transition-colors disabled:opacity-50'
                >
                  Generate
                </button>
              </div>
            </div>
          )}

          {error && (
            <div className='mt-6 flex items-start gap-3 p-4 rounded-xl border border-red-500/30 bg-red-500/10'>
              <AlertCircle className='w-5 h-5 text-red-300 mt-0.5' />
              <div>
                <div className='text-red-200 font-semibold'>Generation error</div>
                <div className='text-red-100/80 text-sm mt-1'>{error}</div>
              </div>
            </div>
          )}

          {loading && (
            <div className='mt-6 rounded-2xl border border-white/10 bg-white/5 p-6 text-center'>
              <div className='inline-block animate-spin rounded-full h-10 w-10 border-b-2 border-white/80 mb-3' />
              <div className='text-white/80 font-semibold'>Generating…</div>
              <div className='text-white/40 text-sm mt-1'>Usually 2–10 seconds</div>
            </div>
          )}

          {generated && (
            <div className='mt-8'>
              <div className='flex flex-col md:flex-row md:items-center md:justify-between gap-3 mb-4'>
                <div>
                  <h2 className='text-xl font-semibold text-white/90'>Generated Client</h2>
                  <p className='text-sm text-white/50 mt-1'>Project: {generated.projectName}</p>
                </div>
                <div className='flex gap-2'>
                  <button
                    type='button'
                    onClick={() => void handleDownloadZip()}
                    className='inline-flex items-center gap-2 px-4 py-2 rounded-xl border border-white/10 bg-white/5 hover:bg-white/10 transition-colors text-white/80'
                  >
                    <Download className='w-4 h-4' />
                    Download ZIP
                  </button>
                  <button
                    type='button'
                    disabled
                    className='px-4 py-2 rounded-xl bg-white text-black font-semibold opacity-50 cursor-not-allowed'
                    title='Coming soon'
                  >
                    Publish to npm
                  </button>
                </div>
              </div>

              <div className='grid grid-cols-1 md:grid-cols-2 gap-4'>
                {Object.entries(generated.files).map(([name, code]) => (
                  <div
                    key={name}
                    className='rounded-2xl overflow-hidden border border-white/10 bg-black/20'
                  >
                    <div className='px-4 py-2 bg-black/30 border-b border-white/10 flex items-center justify-between'>
                      <div className='text-xs font-mono text-white/70'>{name}</div>
                      <button
                        type='button'
                        className='text-xs text-white/50 hover:text-white/80 transition-colors'
                        onClick={() => void navigator.clipboard.writeText(code)}
                      >
                        Copy
                      </button>
                    </div>
                    <pre className='p-4 text-xs font-mono text-white/80 overflow-x-auto max-h-85'>
                      {code}
                    </pre>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
